  DROP TABLE IF EXISTS projects;

  CREATE TABLE projects (
      id                            SERIAL primary key,
      name                          VARCHAR(100) NOT NULL,
      description                   TEXT,
      month_year                    VARCHAR(50) NOT NULL,
      cover_url                     TEXT, 
      page_url                      TEXT,
      github_url                    TEXT,
      rows                          INT,
      cols                       INT,
      created_at                    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols) VALUES ('Petition Portal', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 1, 1);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal2', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 1, 1);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal3', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 2, 2);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal4', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 1, 1);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal5', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 1, 1);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal6', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 2, 4);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal7', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 2, 2);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal8', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 1, 1);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal9', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 1, 1);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal10', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 2, 2);
INSERT INTO projects (name, description, month_year, cover_url, page_url, rows, cols)  VALUES ('Petition Portal11', 'A Petition Portal Page based on the Karen Meme. It was the 2nd Project developed during the Spiced Bootcamp, and the requirements were to build a petition page using Express-Handlebars.', 'April/2022', 'https://auspic.s3.eu-central-1.amazonaws.com/k71UYMULZOYn5dBcr0jc.png','https://karenspetitionportal.herokuapp.com/', 2, 2);
